// Товары магазина. Чтобы изменить ассортимент — редактируйте только этот файл.
// image: путь к фото (положите файл в /images и укажите "images/имя.jpg").
// Если image пустой — карточка покажет красивую заглушку с эмодзи.
const PRODUCTS = [
  {
    id: 1,
    name: "Финики Меджул (Королевские)",
    description: "Крупные, мягкие, карамельно-сладкие. Иордания.",
    price: 6900,
    unit: "500 г",
    image: "images/medjool.jpg",
    emoji: "👑",
  },
  {
    id: 2,
    name: "Финики Сафави",
    description: "Тёмные, нежные, с шоколадными нотами. Саудовская Аравия.",
    price: 4500,
    unit: "500 г",
    image: "images/safawi.jpg",
    emoji: "🍫",
  },
  {
    id: 3,
    name: "Финики Аджва",
    description: "Премиальный сорт из Медины. Мягкие и ароматные.",
    price: 8500,
    unit: "500 г",
    image: "images/ajwa.jpg",
    emoji: "✨",
  },
  {
    id: 4,
    name: "Суккари Муфаттал",
    description: "Мягкие, с медовой сладостью. Саудовская Аравия.",
    price: 4900,
    unit: "500 г",
    image: "images/sukkari-mufattal.jpg",
    emoji: "🍯",
  },
  {
    id: 5,
    name: "Суккари Рутаб",
    description: "Свежие и сочные, тают во рту. Саудовская Аравия.",
    price: 5500,
    unit: "500 г",
    image: "images/sukkari-rutab.jpg",
    emoji: "🌟",
  },
  {
    id: 6,
    name: "Финики в шоколаде",
    description: "Бельгийский тёмный шоколад, вручную.",
    price: 5900,
    unit: "300 г",
    image: "images/choco.jpg",
    emoji: "🎁",
  },
  {
    id: 7,
    name: "Подарочный набор «Двор»",
    description: "Ассорти из 4 сортов в подарочной коробке.",
    price: 14900,
    unit: "1 кг",
    image: "images/gift.jpg",
    emoji: "🌴",
  },
];
